# Generated by Django 4.2.23 on 2025-08-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=100)),
                ('store_phone', models.CharField(max_length=100)),
                ('store_email', models.CharField(max_length=100)),
                ('store_website', models.CharField(max_length=100)),
                ('stor_lat', models.FloatField()),
                ('stor_lon', models.FloatField()),
            ],
        ),
    ]
