# Generated by Django 4.2.23 on 2025-08-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='stor_lat',
            new_name='store_lat',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='stor_lon',
            new_name='store_lon',
        ),
    ]
